name: Deploy Application Docker Image to Azure Web App Service 

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "infrastructure/*"
      - "docs"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Application Image to Azure Container Registry
        id: docker-push
        run: |
          # Convert repo name to lowercase
          repo_name=$(echo "${{ secrets.REPO_NAME }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ${{ secrets.AZURE_LOGIN_SERVER }}/${repo_name}:${{ github.sha }} .
          docker push ${{ secrets.AZURE_LOGIN_SERVER }}/${repo_name}:${{ github.sha }}

      - name: Set Environment Variables
        run: |
          echo "REPO_NAME=$(echo '${{ secrets.REPO_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Debug Repository and Image Name
        run: |
          echo "Repository Name: $REPO_NAME"
          echo "Image Name: ${{ secrets.AZURE_LOGIN_SERVER }}/$REPO_NAME:${{ github.sha }}"

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ineuronfaceapp
          images: ${{ secrets.AZURE_LOGIN_SERVER }}/$(echo '${{ secrets.REPO_NAME }}' | tr '[:upper:]' '[:lower:]'):${{ github.sha }}
